#!/bin/bash
/C/raylib/w64devkit/bin/gcc.exe -o test.exe test.c controles/checkbox.c -s -static -Os -std=c99 -Wall -I/C/raylib/raylib/src -I./objs/ -Iexternal -DPLATFORM_DESKTOP -lraylib -lopengl32 -lgdi32 -lwinmm #-mwindows
./test